### ISSUE TITLE
Introduce HTML5 mode

### ISSUE THREAD

**Issue by bamtor** [google/compact_enc_det#2]
(originally reported by jshin@chromium.org)

When used in conjunction with Chromium, Blink only supports ISO-2022-JP. The detection of other 7-bit encodings and other non-HTML5 encodings should be disabled in CED. We can handle it by introducing HTML5 mode.

**Comment by bamtor** [comment]
https://github.com/google/compact_enc_det/commit/9012c0ab648025dd0f8df14294bf5d6d73793ac9 handles 7-bit encodings other than ISO-20220-JP so that the result will be ASCII-7BIT instead.

**Comment by jungshik** [comment]
Sorry that I made a misleading/confusing bug report. Other than UTF-7, ISO-2022-{KR,CN} and HZ-GB are treated as replacement encoding per WHATWG encoding spec. So, if they're detected by CED, Blink will convert the whole input to a single character U+FFFD. 

Given this,  I think we'd better leave alone the detection of those encodings and let Blink deal with them (convert to U+FFFD).  

UTF-7 is a bit tricky. I'm filing a bug against WHATWG encoding spec so that it's treated the same way as ISO-2022-{KR,CN}, HZ-GB. See whatwg/encoding#68

**Comment by bamtor** [comment]
Let me revert the change. I believe, however, HTML5_MODE is still valid for sanitizing encoding names as filed in https://github.com/google/compact_enc_det/issues/1 I'll keep it and use it for that purpose.

**Comment by JinsukKim** [comment]
e21eb6aed10b9f6e2727f136c52420033214d458 kinds of handled this issue on CED side by returning LATIN if the detected encoding is not supported by WHATWG. This is to make the behavior conform to the standard as well as leave the document intact in such situation.
